codecov:
  branch: main

coverage:
  status:
    project:
      default:
        target: 75%
        threshold: 1%
    patch:
      default:
        target: 75%
        threshold: 1%

ignore:
  - "lib/src/generated/**/*"
  - "example/**/*"
  - "test/**/*"
